/**
 * Mock data for demo/simulation mode.
 * Realistic PR dataset covering all 4 risk levels.
 */

import type { ScoredPR } from "@/types";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();

export const MOCK_PRS: ScoredPR[] = [
  {
    id: 1001,
    number: 847,
    title: "refactor(auth): migrate JWT validation to new middleware stack",
    html_url: "https://github.com/acme/platform/pull/847",
    state: "open",
    draft: false,
    user: { login: "copilot-bot", avatar_url: "", html_url: "" },
    body: "Generated by GitHub Copilot. Migrates all JWT validation logic.",
    created_at: hoursAgo(2),
    updated_at: hoursAgo(1),
    merged_at: null,
    additions: 1240,
    deletions: 18,
    changed_files: 31,
    commits: 1,
    files: [
      { filename: "src/auth/jwt.ts", additions: 340, deletions: 5, changes: 345, status: "modified" },
      { filename: "src/auth/middleware.ts", additions: 280, deletions: 8, changes: 288, status: "modified" },
      { filename: "src/config/security.ts", additions: 120, deletions: 2, changes: 122, status: "modified" },
      { filename: "src/payment/webhook.ts", additions: 80, deletions: 1, changes: 81, status: "modified" },
    ],
    commitList: [
      {
        sha: "abc1",
        commit: {
          author: { name: "Copilot", email: "copilot@github.com", date: hoursAgo(2) },
          message: "refactor: migrate JWT stack\n\nCo-Authored-By: GitHub Copilot <copilot@github.com>",
        },
        author: null,
        coAuthors: ["GitHub Copilot <copilot@github.com>"],
      },
    ],
    scoring: {
      totalScore: 94,
      riskLevel: "critical",
      signals: [
        { signal: "size", score: 100, label: "Very large PR", details: ["1258 lines changed (1240 additions, 18 deletions)", "31 files changed", "+15 bonus: more than 20 files changed"] },
        { signal: "ai_generated", score: 70, label: "Likely AI-generated", details: ["AI co-author detected: GitHub Copilot <copilot@github.com> (+50pts)", "High add/delete ratio: 1240/18 = 68.9 (>20x) (+20pts)"] },
        { signal: "age", score: 0, label: "Very fresh (2h old)", details: ["PR opened 2 hours ago", "Risk window: 4h (low) → 72h (high)"] },
        { signal: "hotspot", score: 100, label: "Risky paths + cross-PR overlap", details: ["4 risky files detected: src/auth/jwt.ts, src/auth/middleware.ts, src/config/security.ts… (+1 more)"] },
      ],
    },
  },
  {
    id: 1002,
    number: 851,
    title: "feat(payments): add Stripe webhook signature verification",
    html_url: "https://github.com/acme/platform/pull/851",
    state: "open",
    draft: false,
    user: { login: "maya-chen", avatar_url: "", html_url: "" },
    body: "Adds HMAC-SHA256 signature verification for all incoming Stripe events.",
    created_at: hoursAgo(38),
    updated_at: hoursAgo(6),
    merged_at: null,
    additions: 420,
    deletions: 12,
    changed_files: 8,
    commits: 5,
    files: [
      { filename: "src/payment/stripe-webhook.ts", additions: 210, deletions: 8, changes: 218, status: "modified" },
      { filename: "src/payment/types.ts", additions: 60, deletions: 2, changes: 62, status: "modified" },
      { filename: "src/admin/billing.ts", additions: 80, deletions: 2, changes: 82, status: "added" },
    ],
    commitList: [
      { sha: "b1", commit: { author: { name: "Maya", email: "maya@acme.com", date: hoursAgo(38) }, message: "feat: add stripe webhook handler" }, author: null, coAuthors: [] },
      { sha: "b2", commit: { author: { name: "Maya", email: "maya@acme.com", date: hoursAgo(30) }, message: "fix: validate signature header" }, author: null, coAuthors: [] },
      { sha: "b3", commit: { author: { name: "Maya", email: "maya@acme.com", date: hoursAgo(20) }, message: "test: add webhook tests" }, author: null, coAuthors: [] },
    ],
    scoring: {
      totalScore: 72,
      riskLevel: "high",
      signals: [
        { signal: "size", score: 41, label: "420 lines changed", details: ["432 lines changed (420 additions, 12 deletions)", "8 files changed"] },
        { signal: "ai_generated", score: 20, label: "Possible AI assistance", details: ["High add/delete ratio: 420/12 = 35.0 (>20x) (+20pts)"] },
        { signal: "age", score: 50, label: "38h old", details: ["PR opened 38 hours ago", "Risk window: 4h (low) → 72h (high)"] },
        { signal: "hotspot", score: 60, label: "Risky paths + cross-PR overlap", details: ["3 risky files detected: src/payment/stripe-webhook.ts, src/payment/types.ts, src/admin/billing.ts"] },
      ],
    },
  },
  {
    id: 1003,
    number: 843,
    title: "chore: bump dependencies — react 18.3, next 14.2, typescript 5.4",
    html_url: "https://github.com/acme/platform/pull/843",
    state: "open",
    draft: false,
    user: { login: "dependabot[bot]", avatar_url: "", html_url: "" },
    body: "Automated dependency update.",
    created_at: hoursAgo(65),
    updated_at: hoursAgo(48),
    merged_at: null,
    additions: 340,
    deletions: 340,
    changed_files: 3,
    commits: 1,
    files: [
      { filename: "package.json", additions: 12, deletions: 12, changes: 24, status: "modified" },
      { filename: "package-lock.json", additions: 328, deletions: 328, changes: 656, status: "modified" },
    ],
    commitList: [
      { sha: "c1", commit: { author: { name: "dependabot", email: "bot@github.com", date: hoursAgo(65) }, message: "chore: bump dependencies" }, author: null, coAuthors: [] },
    ],
    scoring: {
      totalScore: 52,
      riskLevel: "high",
      signals: [
        { signal: "size", score: 33, label: "340 lines changed", details: ["680 lines changed (340 additions, 340 deletions)", "3 files changed"] },
        { signal: "ai_generated", score: 0, label: "No AI indicators", details: ["No AI generation indicators detected"] },
        { signal: "age", score: 90, label: "65h old", details: ["PR opened 65 hours ago", "Risk window: 4h (low) → 72h (high)"] },
        { signal: "hotspot", score: 10, label: "1 cross-PR file", details: ["1 file also modified in other open PRs: package.json"] },
      ],
    },
  },
  {
    id: 1004,
    number: 855,
    title: "feat(ui): add dark mode toggle to user settings page",
    html_url: "https://github.com/acme/platform/pull/855",
    state: "open",
    draft: false,
    user: { login: "james-park", avatar_url: "", html_url: "" },
    body: "Adds a dark/light mode toggle. Saves preference to localStorage.",
    created_at: hoursAgo(14),
    updated_at: hoursAgo(2),
    merged_at: null,
    additions: 185,
    deletions: 22,
    changed_files: 6,
    commits: 3,
    files: [
      { filename: "src/components/SettingsPage.tsx", additions: 80, deletions: 10, changes: 90, status: "modified" },
      { filename: "src/components/ThemeToggle.tsx", additions: 75, deletions: 8, changes: 83, status: "added" },
      { filename: "src/styles/globals.css", additions: 30, deletions: 4, changes: 34, status: "modified" },
    ],
    commitList: [
      { sha: "d1", commit: { author: { name: "James", email: "james@acme.com", date: hoursAgo(14) }, message: "feat: add theme toggle component" }, author: null, coAuthors: [] },
      { sha: "d2", commit: { author: { name: "James", email: "james@acme.com", date: hoursAgo(8) }, message: "style: refine toggle animation" }, author: null, coAuthors: [] },
      { sha: "d3", commit: { author: { name: "James", email: "james@acme.com", date: hoursAgo(3) }, message: "fix: persist theme on reload" }, author: null, coAuthors: [] },
    ],
    scoring: {
      totalScore: 31,
      riskLevel: "medium",
      signals: [
        { signal: "size", score: 16, label: "185 lines changed", details: ["207 lines changed (185 additions, 22 deletions)", "6 files changed"] },
        { signal: "ai_generated", score: 0, label: "No AI indicators", details: ["No AI generation indicators detected"] },
        { signal: "age", score: 15, label: "14h old", details: ["PR opened 14 hours ago", "Risk window: 4h (low) → 72h (high)"] },
        { signal: "hotspot", score: 0, label: "No hotspot files", details: ["No risky paths or file overlaps detected"] },
      ],
    },
  },
  {
    id: 1005,
    number: 858,
    title: "docs: update API reference for v2 endpoints",
    html_url: "https://github.com/acme/platform/pull/858",
    state: "open",
    draft: false,
    user: { login: "sara-wilson", avatar_url: "", html_url: "" },
    body: "Updates API docs to reflect the new v2 endpoint signatures.",
    created_at: hoursAgo(5),
    updated_at: hoursAgo(1),
    merged_at: null,
    additions: 42,
    deletions: 18,
    changed_files: 2,
    commits: 2,
    files: [
      { filename: "docs/api-reference.md", additions: 38, deletions: 16, changes: 54, status: "modified" },
      { filename: "docs/changelog.md", additions: 4, deletions: 2, changes: 6, status: "modified" },
    ],
    commitList: [
      { sha: "e1", commit: { author: { name: "Sara", email: "sara@acme.com", date: hoursAgo(5) }, message: "docs: update v2 api reference" }, author: null, coAuthors: [] },
      { sha: "e2", commit: { author: { name: "Sara", email: "sara@acme.com", date: hoursAgo(2) }, message: "docs: add deprecation notes" }, author: null, coAuthors: [] },
    ],
    scoring: {
      totalScore: 9,
      riskLevel: "low",
      signals: [
        { signal: "size", score: 0, label: "Small PR", details: ["60 lines changed (42 additions, 18 deletions)", "2 files changed"] },
        { signal: "ai_generated", score: 0, label: "No AI indicators", details: ["No AI generation indicators detected"] },
        { signal: "age", score: 1, label: "5h old", details: ["PR opened 5 hours ago", "Risk window: 4h (low) → 72h (high)"] },
        { signal: "hotspot", score: 0, label: "No hotspot files", details: ["No risky paths or file overlaps detected"] },
      ],
    },
  },
  {
    id: 1006,
    number: 849,
    title: "fix(api): handle 429 rate limit response with exponential backoff",
    html_url: "https://github.com/acme/platform/pull/849",
    state: "open",
    draft: true,
    user: { login: "lei-zhang", avatar_url: "", html_url: "" },
    body: "WIP: adds retry logic with exponential backoff for rate-limited API calls.",
    created_at: hoursAgo(20),
    updated_at: hoursAgo(1),
    merged_at: null,
    additions: 88,
    deletions: 14,
    changed_files: 4,
    commits: 4,
    files: [
      { filename: "src/lib/apiClient.ts", additions: 60, deletions: 10, changes: 70, status: "modified" },
      { filename: "src/lib/retry.ts", additions: 28, deletions: 4, changes: 32, status: "added" },
    ],
    commitList: [
      { sha: "f1", commit: { author: { name: "Lei", email: "lei@acme.com", date: hoursAgo(20) }, message: "feat: add retry helper" }, author: null, coAuthors: [] },
      { sha: "f2", commit: { author: { name: "Lei", email: "lei@acme.com", date: hoursAgo(15) }, message: "feat: integrate retry in apiClient" }, author: null, coAuthors: [] },
      { sha: "f3", commit: { author: { name: "Lei", email: "lei@acme.com", date: hoursAgo(10) }, message: "fix: correct backoff formula" }, author: null, coAuthors: [] },
      { sha: "f4", commit: { author: { name: "Lei", email: "lei@acme.com", date: hoursAgo(2) }, message: "wip: add tests" }, author: null, coAuthors: [] },
    ],
    scoring: {
      totalScore: 18,
      riskLevel: "low",
      signals: [
        { signal: "size", score: 4, label: "88 lines changed", details: ["102 lines changed (88 additions, 14 deletions)", "4 files changed"] },
        { signal: "ai_generated", score: 0, label: "No AI indicators", details: ["No AI generation indicators detected"] },
        { signal: "age", score: 24, label: "20h old", details: ["PR opened 20 hours ago", "Risk window: 4h (low) → 72h (high)"] },
        { signal: "hotspot", score: 0, label: "No hotspot files", details: ["No risky paths or file overlaps detected"] },
      ],
    },
  },
];

export const MOCK_REPO = { owner: "acme", repo: "platform", login: "demo-user" };

export const MOCK_RATE_LIMIT = { limit: 5000, remaining: 4847, reset: 0, used: 153 };
