import { computeAISignal } from "@/lib/signals/ai-generated";
import type { GitHubPR, PRCommit } from "@/types";

const basePR: GitHubPR = {
  id: 1,
  number: 1,
  title: "Test PR",
  html_url: "https://github.com/owner/repo/pull/1",
  state: "open",
  draft: false,
  user: { login: "user", avatar_url: "", html_url: "" },
  body: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  merged_at: null,
  additions: 50,
  deletions: 20,
  changed_files: 3,
  commits: 2,
  commitList: [],
};

const makeCommit = (
  dateIso: string,
  coAuthors: string[] = []
): PRCommit => ({
  sha: "abc",
  commit: {
    author: { name: "User", email: "user@example.com", date: dateIso },
    message: "feat: add thing",
  },
  author: null,
  coAuthors,
});

describe("computeAISignal", () => {
  it("returns score 0 for clean human PR", () => {
    const result = computeAISignal(basePR);
    expect(result.score).toBe(0);
    expect(result.signal).toBe("ai_generated");
  });

  it("adds coAuthorPoints when AI co-author detected", () => {
    const pr: GitHubPR = {
      ...basePR,
      commitList: [
        makeCommit("2024-01-01T10:00:00Z", [
          "GitHub Copilot <copilot@github.com>",
        ]),
      ],
    };
    const result = computeAISignal(pr);
    expect(result.score).toBeGreaterThanOrEqual(50);
  });

  it("adds commitBurstPoints when ≥3 commits in ≤10 minutes", () => {
    const base = new Date("2024-01-01T10:00:00Z").getTime();
    const pr: GitHubPR = {
      ...basePR,
      commits: 3,
      commitList: [
        makeCommit(new Date(base).toISOString()),
        makeCommit(new Date(base + 3 * 60 * 1000).toISOString()), // +3 min
        makeCommit(new Date(base + 7 * 60 * 1000).toISOString()), // +7 min
      ],
    };
    const result = computeAISignal(pr);
    expect(result.score).toBeGreaterThanOrEqual(30);
  });

  it("does NOT add commitBurstPoints for slow commits (>10 min apart)", () => {
    const base = new Date("2024-01-01T10:00:00Z").getTime();
    const pr: GitHubPR = {
      ...basePR,
      commits: 3,
      commitList: [
        makeCommit(new Date(base).toISOString()),
        makeCommit(new Date(base + 20 * 60 * 1000).toISOString()), // +20 min
        makeCommit(new Date(base + 40 * 60 * 1000).toISOString()), // +40 min
      ],
    };
    const result = computeAISignal(pr);
    expect(result.score).toBe(0);
  });

  it("adds ratioAnomalyPoints for high add/delete ratio", () => {
    const pr: GitHubPR = {
      ...basePR,
      additions: 500,
      deletions: 10, // ratio = 50, above threshold of 20
    };
    const result = computeAISignal(pr);
    expect(result.score).toBeGreaterThanOrEqual(20);
  });

  it("adds ratioAnomalyPoints for pure additions > 200 with zero deletions", () => {
    const pr: GitHubPR = {
      ...basePR,
      additions: 300,
      deletions: 0,
    };
    const result = computeAISignal(pr);
    expect(result.score).toBeGreaterThanOrEqual(20);
  });

  it("caps score at 100", () => {
    const base = new Date("2024-01-01T10:00:00Z").getTime();
    const pr: GitHubPR = {
      ...basePR,
      additions: 1000,
      deletions: 0,
      commits: 3,
      commitList: [
        makeCommit(new Date(base).toISOString(), ["GitHub Copilot <copilot@github.com>"]),
        makeCommit(new Date(base + 2 * 60 * 1000).toISOString()),
        makeCommit(new Date(base + 4 * 60 * 1000).toISOString()),
      ],
    };
    const result = computeAISignal(pr);
    expect(result.score).toBeLessThanOrEqual(100);
  });

  it("detects AI marker in PR body", () => {
    const pr: GitHubPR = {
      ...basePR,
      body: "Generated by Claude AI assistant",
    };
    const result = computeAISignal(pr);
    expect(result.score).toBeGreaterThanOrEqual(50);
  });
});
