#!/usr/bin/env bash
#
# deploy-wizard.sh — Push Halp ke GitHub dan deploy ke Vercel
# Generated by the /wizard skill.
#
# Jalankan dari root project:
#   bash scripts/deploy-wizard.sh

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do.\n'
  printf '  Stop any time with Ctrl-C.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
ok()   { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open browser — visit manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open browser — visit manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  ok "wrote $key → $ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "GitHub secrets set: ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Halp — GitHub push & Vercel deploy"

# ── Stage 1: Buat GitHub repo ─────────────────────────────────────────────
stage "Buat GitHub repository"
say "Kita perlu repo GitHub publik untuk source code Halp."
say ""
open_url "https://github.com/new"
say ""
step "Isi Repository name: halp"
step "Pilih Public"
step "JANGAN centang 'Initialize this repository' (kosongkan semua)"
step "Klik 'Create repository'"
step "Salin URL repo yang muncul (contoh: https://github.com/namaUser/halp)"
say ""
ask GITHUB_REPO_URL "Paste URL GitHub repo kamu:"

if [[ -z "$GITHUB_REPO_URL" ]]; then
  warn "URL kosong, skip push GitHub."
  SKIPPED+=("GitHub push — jalankan ulang wizard setelah buat repo")
else
  ok "URL repo: $GITHUB_REPO_URL"
fi

pause

# ── Stage 2: Init git & push ──────────────────────────────────────────────
stage "Init git dan push ke GitHub"

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
say "Project directory: $PROJECT_DIR"
say ""

if [[ -z "$GITHUB_REPO_URL" ]]; then
  warn "Lewat tahap ini karena URL repo kosong."
else
  cd "$PROJECT_DIR"

  if [[ ! -d ".git" ]]; then
    say "Inisialisasi git repository..."
    git init -b main
    ok "git init"
  else
    ok "git sudah ada"
  fi

  # Pastikan .gitignore ada
  if ! grep -q "^\.env\.local$" .gitignore 2>/dev/null; then
    printf '\n.env.local\n' >> .gitignore
    ok "tambah .env.local ke .gitignore"
  fi

  git add -A
  git status --short | head -20
  say ""

  if confirm "Lanjut commit semua file di atas?"; then
    git commit -m "feat: initial commit — Halp PR risk radar" 2>/dev/null || \
      git commit --allow-empty -m "feat: initial commit — Halp PR risk radar"
    ok "commit berhasil"
  fi

  # Set remote
  if git remote get-url origin >/dev/null 2>&1; then
    git remote set-url origin "$GITHUB_REPO_URL"
    ok "remote origin diperbarui → $GITHUB_REPO_URL"
  else
    git remote add origin "$GITHUB_REPO_URL"
    ok "remote origin ditambahkan → $GITHUB_REPO_URL"
  fi

  say ""
  say "Push ke GitHub..."
  if git push -u origin main 2>&1; then
    ok "push berhasil ke $GITHUB_REPO_URL"
  else
    warn "push gagal. Coba:"
    note "  git push -u origin main --force"
    note "atau pastikan kamu sudah login git dengan Personal Access Token."
    pause "Selesaikan push secara manual, lalu tekan Enter untuk lanjut."
  fi
fi

pause

# ── Stage 3: Login Vercel ─────────────────────────────────────────────────
stage "Login Vercel CLI"
say "Kita pakai Vercel CLI yang sudah terinstall untuk deploy."
say ""

if ! vercel whoami >/dev/null 2>&1; then
  say "Kamu belum login ke Vercel. Akan membuka browser untuk login..."
  say ""
  vercel login
  ok "Vercel login selesai"
else
  VERCEL_USER=$(vercel whoami 2>/dev/null || echo "unknown")
  ok "Sudah login sebagai: $VERCEL_USER"
fi

pause

# ── Stage 4: Deploy ke Vercel ─────────────────────────────────────────────
stage "Deploy ke Vercel"

cd "$PROJECT_DIR"
say "Menjalankan: vercel --prod"
say ""
note "Ketika Vercel CLI bertanya, jawab:"
note "  • Set up and deploy? → Y"
note "  • Which scope? → pilih akunmu"
note "  • Link to existing project? → N"
note "  • What's your project's name? → halp"
note "  • In which directory is your code? → . (titik, Enter)"
note "  • Want to modify these settings? → N"
say ""
pause "Siap deploy? (tekan Enter)"

vercel --prod

say ""
ok "Deploy selesai!"

pause

# ── Stage 5: Custom domain halp.vercel.app ────────────────────────────────
stage "Cek URL deploy"

say "URL default Vercel biasanya: https://halp.vercel.app"
say "Vercel memberi subdomain otomatis berdasarkan nama project."
say ""
note "Jika nama project kamu 'halp', URL-nya AKAN jadi https://halp.vercel.app"
note "asalkan nama itu belum dipakai orang lain."
say ""
step "Buka dashboard Vercel untuk konfirmasi URL:"
open_url "https://vercel.com/dashboard"
say ""
step "Klik project 'halp'"
step "Lihat tab 'Deployments' — copy URL produksi yang muncul"
say ""
ask VERCEL_URL "URL produksi Halp:"

if [[ -n "$VERCEL_URL" ]]; then
  ok "App live di: $VERCEL_URL"
  say ""
  say "Test buka sekarang:"
  open_url "$VERCEL_URL"
fi

say ""
say "Jika URL bukan halp.vercel.app, kamu bisa ganti nama project:"
step "Dashboard Vercel → project → Settings → General → Project Name → ubah ke 'halp'"
step "Kemudian redeploy: vercel --prod"
say ""
note "Catatan: halp.vercel.app hanya tersedia jika nama itu belum diambil."
note "Kalau sudah dipakai, Vercel akan beri suffix otomatis."

pause

# ── Done ──────────────────────────────────────────────────────────────────
finish

printf '  %sHalp sudah live!%s\n' "$BOLD" "$RESET"
if [[ -n "${VERCEL_URL:-}" ]]; then
  printf '  %s%s%s\n\n' "$GREEN" "$VERCEL_URL" "$RESET"
fi
